WITH CTE AS (
    SELECT CAR_ID, '대여중' AS AVAILABILITY
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE '2022-10-16' BETWEEN START_DATE AND END_DATE
)
SELECT 
    a.CAR_ID, 
    COALESCE(b.AVAILABILITY, '대여 가능') AS AVAILABILITY
FROM 
    (SELECT DISTINCT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY) a
LEFT JOIN CTE b ON a.CAR_ID = b.CAR_ID
ORDER BY 
    a.CAR_ID DESC;