WITH CTE AS (
    SELECT CAR_ID, COUNT(*) AS RECORDS
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
)
SELECT 
    DATE_FORMAT(a.START_DATE, '%m') AS MONTH, 
    a.CAR_ID, 
    COUNT(*) AS RECORDS
FROM 
    CAR_RENTAL_COMPANY_RENTAL_HISTORY a
JOIN 
    CTE b ON a.CAR_ID = b.CAR_ID
WHERE 
    a.START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY 
    DATE_FORMAT(a.START_DATE, '%Y-%m'), a.CAR_ID
ORDER BY 
    MONTH ASC, a.CAR_ID DESC;